training:
  data_path: "/oscar/data/jtompki1/cli277/nyuv2/nyuv2"

  batch_size: 4
  epochs: 150
  warmup_epochs: 5

  optimizer:
    type: "adam"
    lr: 1e-4
    weight_decay: 1e-7
  
  lr_scheduler:
    type: "plateau"
    mode: "min"
    factor: 0.1
    patience: 1

  output_dir: "./checkpoints_dpt"
  backbone: "vitl16_384"
  device: "cuda"
  debug: true
  # Use a standard 640x480 resolution
  input_width: 640
  input_height: 480

logging:
  level: "INFO"

profiling:
  enable: false
  steps_to_profile: 5
  export_trace: "./profile_trace.json"